"use client";
import {useState} from "react";
import type {PaperResearch} from "@/lib/assistant/paper-research";
import type {replayStrategy} from "@/lib/assistant/strategy-replay";
type Run=ReturnType<typeof replayStrategy>;
type Report={observedAtMs:number;research:PaperResearch;limitations:string;replays:{symbol:string;source:string;baseline:Run;stressed:Run;holdout:Run}[]};
export function StrategyValidation(){
  const [report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const download=()=>{if(!report)return;const blob=new Blob([JSON.stringify(report,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="lucian-historical-validation.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const run=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/assistant/strategy-validation",{cache:"no-store",signal:AbortSignal.timeout(60000)});const b=await r.json();if(!r.ok||!b.ok)throw Error(b.error??"Validation unavailable.");setReport(b);}catch(e){setError(e instanceof Error?e.message:"Validation unavailable.");}finally{setBusy(false);}};
  return <section aria-label="Historical strategy validation" className="space-y-3 border-t border-line pt-4"><h3 className="font-medium">Research and longer strategy validation</h3><p>Read-only historical replay: about 40 days of hourly BTC/ETH data, baseline and higher costs, plus a last-week segment. Does not start a session or submit orders.</p><button type="button" disabled={busy} onClick={()=>void run()} className="focus-ring rounded-lg border border-line px-3 py-2 disabled:opacity-50">{busy?"Checking research…":"Run historical validation"}</button>{error&&<p role="alert">{error}</p>}{report&&<><button type="button" onClick={download} className="focus-ring rounded-lg border border-line px-3 py-2">Export historical report</button><p>{report.limitations}</p><div className="overflow-x-auto"><table><caption>Historical reference strategy results</caption><thead><tr>{["Market","Case","Hours","Net USDT","Trades","Wins","Costs USDT","Drawdown USDT"].map(t=><th key={t} className="px-2 text-left">{t}</th>)}</tr></thead><tbody>{report.replays.flatMap(r=>(["baseline","stressed","holdout"] as const).map(k=><tr key={r.symbol+k}><td><a href={r.source} target="_blank" rel="noreferrer">{r.symbol}</a></td><td>{k}</td><td>{r[k].bars}</td><td>{r[k].netUsdt.toFixed(2)}</td><td>{r[k].trades}</td><td>{r[k].wins}</td><td>{r[k].costsUsdt.toFixed(2)}</td><td>{r[k].maxDrawdownUsdt.toFixed(2)}</td></tr>))}</tbody></table></div><details><summary>Independent research context</summary>{report.research.context?.map((c,i)=><p key={i}><a href={c.source} target="_blank" rel="noreferrer">{c.kind==="sentiment"?"Alternative.me Bitcoin Fear & Greed":"Coinbase USD reference"}</a> · {c.symbol}: {c.value} · {new Date(c.atMs).toLocaleString()}</p>)}{report.research.warnings.map((w,i)=><p key={i}>{w}</p>)}</details><p>Collected {new Date(report.observedAtMs).toLocaleString()}. No model inference credits used by this replay.</p></>}</section>;
}
