// Bidirectional code converter (Repomix-style):
//   projectToCode()  -> single text bundle of all files with markers
//   codeToProject()  -> reconstruct ProjectFile[] from the bundle
//
// The bundle format is intentionally robust so it can survive being pasted
// through chat tools (DeepSeek, ChatGPT, etc.). We support multiple input
// shapes:
//   1. Our own strict bundle format (80-char `=` separators + `FILE:` headers)
//   2. Markdown-fenced bundles (```language\n...``` blocks preceded by a path comment)
//   3. A single raw source file with no metadata (we explain what's missing)

import type { FileEntry, ProjectFile } from "@/types/workspace";
import { base64ToBytes, bytesToBase64 } from "./filesystem";

export const BUNDLE_HEADER = `# ============================================================
# PROJECT CODE BUNDLE
# Generated by DevWorkspace Code Converter
# Format: <path> | <encoding> | <size>
#   encoding: text | base64
#   size: byte length of decoded content
# ============================================================

`;

export interface BundleOptions {
  includeHeader?: boolean;
  /** Optional project name to embed in the bundle header. */
  projectName?: string;
}

/** Pack a list of project files into a single text bundle. */
export function projectToCode(files: ProjectFile[], opts: BundleOptions = {}): string {
  const { includeHeader = true, projectName = "Untitled Project" } = opts;
  const parts: string[] = [];

  if (includeHeader) {
    parts.push(
      `# Project: ${projectName}\n# Files: ${files.length}\n# Generated: ${new Date().toISOString()}\n`,
    );
    parts.push(BUNDLE_HEADER);

    // File manifest for quick scanning.
    parts.push("# --- MANIFEST ---\n");
    for (const f of files) {
      const encoding = f.binary ? "base64" : "text";
      const size = f.binary
        ? base64ToBytes(f.content.split(",")[1] ?? "").length
        : new TextEncoder().encode(f.content).length;
      parts.push(`# ${f.path} | ${encoding} | ${size}\n`);
    }
    parts.push("\n# --- FILES ---\n\n");
  }

  for (const f of files) {
    const sep = "=".repeat(80);
    const encoding = f.binary ? "base64" : "text";
    parts.push(`${sep}\n`);
    parts.push(`FILE: ${f.path}\n`);
    parts.push(`ENCODING: ${encoding}\n`);
    if (f.mime) parts.push(`MIME: ${f.mime}\n`);
    parts.push(`${sep}\n\n`);

    if (f.binary) {
      const b64 = f.content.split(",")[1] ?? "";
      const wrapped = b64.match(/.{1,76}/g)?.join("\n") ?? b64;
      parts.push(wrapped);
      parts.push("\n\n");
    } else {
      parts.push(f.content);
      if (!f.content.endsWith("\n")) parts.push("\n");
      parts.push("\n");
    }
  }

  return parts.join("");
}

interface ParsedFile {
  path: string;
  encoding: "text" | "base64";
  mime?: string;
  content: string;
}

export interface ReconstructionResult {
  files: ProjectFile[];
  /** Diagnostic message — null when reconstruction was clean. */
  diagnostic: string | null;
  /** Whether the input was recognized at all. */
  recognized: boolean;
  /** The detection strategy that produced these files. */
  strategy: "bundle" | "markdown-fences" | "single-file" | "none";
}

/** Reconstruct ProjectFile[] from a bundle. Accepts multiple input shapes
 *  and returns a diagnostic explaining what was found (or not). */
export function codeToProject(bundle: string): ReconstructionResult {
  const trimmed = bundle.trim();
  if (!trimmed) {
    return {
      files: [],
      diagnostic: "Input is empty. Paste a code bundle (from this converter or from a tool like DeepSeek/ChatGPT) to reconstruct a project.",
      recognized: false,
      strategy: "none",
    };
  }

  // Strategy 1: strict bundle format with 80-char `=` separators.
  const bundleFiles = parseStrictBundle(bundle);
  if (bundleFiles.length > 0) {
    return {
      files: bundleFiles.map(toProjectFile),
      diagnostic: bundleFiles.length === 1
        ? `Recognized 1 file in DevWorkspace bundle format. If you expected more, ensure each file is wrapped in an 80-character "=" separator with a "FILE:" header.`
        : null,
      recognized: true,
      strategy: "bundle",
    };
  }

  // Strategy 2: Markdown-fenced code blocks with path comments.
  const mdFiles = parseMarkdownFences(bundle);
  if (mdFiles.length > 0) {
    return {
      files: mdFiles.map(toProjectFile),
      diagnostic: mdFiles.length === 1
        ? `Found 1 Markdown code block. The path was inferred from a preceding comment (e.g. \`// src/App.tsx\` or \`<!-- index.html -->\`). If the path is wrong, prefix each block with a comment containing the full file path.`
        : null,
      recognized: true,
      strategy: "markdown-fences",
    };
  }

  // Strategy 3: single raw source file with no metadata.
  // We sniff the content to guess a filename + extension.
  const guess = guessSingleFile(trimmed);
  if (guess) {
    return {
      files: [toProjectFile(guess)],
      diagnostic: `The input looks like a single source file but does not include any path or bundle markers. I inferred the filename "${guess.path}" from the content. To reconstruct multiple files, either:\n  • Use the Project → Code direction in this converter to produce a properly-formatted bundle.\n  • Prefix each code block with a comment containing the full file path, e.g. \`// src/components/Button.tsx\`.`,
      recognized: true,
      strategy: "single-file",
    };
  }

  // Strategy 4: nothing recognizable.
  return {
    files: [],
    diagnostic: `Could not recognize the input as a project bundle. The input must either be:\n  • A DevWorkspace bundle (80-char "=" separators with "FILE:" headers)\n  • Markdown with fenced code blocks, each preceded by a path comment\n  • A single source file (in which case we'll guess the filename from content)\n\nWhat was found: ${describeInput(trimmed)}`,
    recognized: false,
    strategy: "none",
  };
}

function parseStrictBundle(bundle: string): ParsedFile[] {
  const files: ParsedFile[] = [];
  const blocks = bundle.split(/^={80}$/m);
  for (const block of blocks) {
    const match = block.match(
      /^[\r\n]*FILE:\s*(\S+)\s*\nENCODING:\s*(\S+)\s*\n(?:MIME:\s*(\S+)\s*\n)?[\r\n]+([\s\S]*)$/,
    );
    if (!match) continue;
    const [, path, encoding, mime, body] = match;
    let content = body.replace(/\n+$/, "");
    if (encoding === "base64") {
      const b64 = content.replace(/\s+/g, "");
      const dataUrl = `data:${mime ?? "application/octet-stream"};base64,${b64}`;
      files.push({ path, encoding: "base64", mime, content: dataUrl });
    } else {
      files.push({ path, encoding: "text", content });
    }
  }
  return files;
}

function parseMarkdownFences(bundle: string): ParsedFile[] {
  const files: ParsedFile[] = [];
  // Match ```lang\n...\n``` blocks, optionally preceded by a comment line
  // like `// path/to/file.tsx` or `<!-- path/to/file.html -->` or `# path/to/file.py`.
  const fenceRe = /(?:^|\n)(?:(?:\/\/\s*([^\n]+?)\s*\n)|(?:<!--\s*([^\n]+?)\s*-->\s*\n)|(?:#\s*([^\n]+?)\s*\n)|(?:\/\*\s*([^\n]+?)\s*\/\*\s*\n))?\s*```[\w-]*\n([\s\S]*?)\n```/g;
  let m: RegExpExecArray | null;
  while ((m = fenceRe.exec(bundle)) !== null) {
    const path = (m[1] || m[2] || m[3] || m[4] || "").trim();
    const body = m[5];
    if (!body.trim()) continue;
    // If no path comment, try to guess from language tag (next iteration).
    if (!path) continue;
    files.push({ path: cleanPath(path), encoding: "text", content: body });
  }
  return files;
}

function cleanPath(p: string): string {
  // Strip leading "./" and surrounding quotes/whitespace.
  return p.replace(/^["'`]|["'`]$/g, "").replace(/^\.\//, "").trim();
}

function guessSingleFile(content: string): ParsedFile | null {
  // Heuristics: detect language and pick a sensible filename.
  const firstLine = content.split("\n")[0] ?? "";
  const looksLikeDoctype = /<!doctype html>/i.test(firstLine);
  if (looksLikeDoctype || /<html[\s>]/i.test(content.slice(0, 500))) {
    return { path: "index.html", encoding: "text", content };
  }
  if (/^<\?xml/.test(firstLine)) {
    return { path: "document.xml", encoding: "text", content };
  }
  // React (JSX/TSX) — check before Python because `import X from 'y'` is
  // valid in both.
  if (
    /^import\s+React|^\s*export\s+default\s+function|^\s*function\s+\w+\s*\([^)]*\)\s*\{[\s\S]*return\s*</.test(content) ||
    /<\w+\s+className=|<\/\w+>/.test(content)
  ) {
    if (content.includes(": ") && /interface\s+\w+|type\s+\w+\s*=/.test(content)) {
      return { path: "App.tsx", encoding: "text", content };
    }
    return { path: "App.jsx", encoding: "text", content };
  }
  if (/^import\s+Vue|^<template>|^export\s+default\s*\{[\s\S]*template:/.test(content)) {
    return { path: "App.vue", encoding: "text", content };
  }
  if (/^package\s+\w+|^func\s+\w+|^import\s+\(/.test(content)) {
    return { path: "main.go", encoding: "text", content };
  }
  // Python — only if `import` is bare (no `from` after) OR `def`/`from X import`.
  if (/^def\s+\w+|^from\s+\w+\s+import/.test(content)) {
    return { path: "main.py", encoding: "text", content };
  }
  if (/^import\s+\w+\s*$/.test(content)) {
    return { path: "main.py", encoding: "text", content };
  }
  if (/^\/\*\*|^\s*\*\/|^\s*public\s+class\s+\w+/.test(content)) {
    return { path: "Main.java", encoding: "text", content };
  }
  if (/^\s*\{\s*"name"\s*:|^\s*\{[\s\S]*"scripts"\s*:/.test(content)) {
    return { path: "package.json", encoding: "text", content };
  }
  if (/^\s*[{[]/.test(content)) {
    return { path: "data.json", encoding: "text", content };
  }
  if (/^\s*(SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)\s+/i.test(content)) {
    return { path: "schema.sql", encoding: "text", content };
  }
  if (/^\s*({|}|\.|#|@media|@import)/.test(content) && /[:;{}]/.test(content)) {
    return { path: "styles.css", encoding: "text", content };
  }
  if (/^#!\/(usr\/|bin\/)/.test(firstLine)) {
    return { path: "script.sh", encoding: "text", content };
  }
  // Default: assume plain text.
  if (content.length > 0) {
    return { path: "untitled.txt", encoding: "text", content };
  }
  return null;
}

function describeInput(content: string): string {
  const lines = content.split("\n").length;
  const chars = content.length;
  const hasFences = /```/.test(content);
  const hasFileHeaders = /^FILE:/m.test(content);
  const hasEqualSeps = /^={40,}$/m.test(content);
  return `${chars} chars, ${lines} lines. Markdown fences: ${hasFences}. FILE: headers: ${hasFileHeaders}. Long "=" separators: ${hasEqualSeps}.`;
}

function toProjectFile(parsed: ParsedFile): ProjectFile {
  const size = parsed.encoding === "base64"
    ? Math.floor(((parsed.content.split(",")[1] ?? "").length * 3) / 4)
    : new TextEncoder().encode(parsed.content).length;
  return {
    path: parsed.path,
    content: parsed.content,
    binary: parsed.encoding === "base64",
    mime: parsed.mime,
    size,
    updatedAt: Date.now(),
    loaded: true,
  };
}

/** Convenience: estimate the on-disk size of a bundle. */
export function bundleByteSize(bundle: string): number {
  return new TextEncoder().encode(bundle).length;
}

/** Self-test for the round-trip. */
export function selfTest(): boolean {
  const sample: ProjectFile[] = [
    {
      path: "src/hello.txt",
      content: "Hello, world!\n",
      binary: false,
      size: 0,
      updatedAt: Date.now(),
    },
  ];
  const bundle = projectToCode(sample, { projectName: "self-test" });
  const restored = codeToProject(bundle);
  if (restored.files.length !== sample.length) return false;
  return restored.files[0].content === sample[0].content;
}

/** Build a hierarchical preview tree (for the reconstruction preview UI). */
export function buildReconstructionPreview(files: ProjectFile[]): string {
  if (files.length === 0) return "(no files)";
  const lines: string[] = [];
  type TreeNode = { [key: string]: TreeNode | null };
  const tree: TreeNode = {};
  for (const f of files) {
    const parts = f.path.split("/");
    let node: TreeNode = tree;
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const isLast = i === parts.length - 1;
      if (isLast) {
        node[part] = null;
      } else {
        node[part] = node[part] ?? {};
        node = node[part] as TreeNode;
      }
    }
  }
  function render(node: Record<string, unknown>, prefix: string) {
    const keys = Object.keys(node).sort();
    for (let i = 0; i < keys.length; i++) {
      const key = keys[i];
      const isLast = i === keys.length - 1;
      const child = node[key];
      const branch = isLast ? "└── " : "├── ";
      if (child === null) {
        lines.push(`${prefix}${branch}${key}`);
      } else {
        lines.push(`${prefix}${branch}${key}/`);
        render(child as Record<string, unknown>, prefix + (isLast ? "    " : "│   "));
      }
    }
  }
  lines.push("project/");
  render(tree, "");
  return lines.join("\n");
}

// Suppress unused import warning for FileEntry (kept for type re-export).
export type { FileEntry };
void bytesToBase64;
